services:

  db:
    image: postgis/postgis:15-3.3
    container_name: farmland_postgis
    restart: unless-stopped

    environment:
      POSTGRES_USER: ${POSTGRES_USER:-postgres}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD:-0000}
      POSTGRES_DB: ${POSTGRES_DB:-farmland_db}

    ports:
      - "5432:5432"

    volumes:
      - postgres_data:/var/lib/postgresql/data

    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres -d farmland_db"]
      interval: 10s
      timeout: 5s
      retries: 5


  redis:
    image: redis:7-alpine
    container_name: farmland_redis
    restart: unless-stopped

    ports:
      - "6379:6379"


  backend:
    build:
      context: .
      dockerfile: backend/Dockerfile

    container_name: farmland_backend
    restart: unless-stopped

    ports:
      - "8000:8000"

    depends_on:
      db:
        condition: service_healthy
      redis:
        condition: service_started

    environment:
      DATABASE_URL: postgresql://${POSTGRES_USER:-postgres}:${POSTGRES_PASSWORD:-0000}@db:5432/${POSTGRES_DB:-farmland_db}
      REDIS_URL: redis://redis:6379/0
      EE_CREDENTIALS_PATH: /app/gee_service_account.json

    volumes:
      - ./backend:/app/backend
      - ./alembic:/app/alembic
      - ./alembic.ini:/app/alembic.ini
      - ./gee_service_account.json:/app/gee_service_account.json:ro


  frontend:
    build:
      context: .
      dockerfile: frontend/Dockerfile

    container_name: farmland_frontend
    restart: unless-stopped

    ports:
      - "5173:5173"

    depends_on:
      backend:
        condition: service_started

    environment:
      VITE_API_BASE_URL: http://localhost:8000/api

    volumes:
      - ./frontend:/app
      - /app/node_modules


volumes:
  postgres_data: