"""Add field comments and refine roles

Revision ID: e6f84edec125
Revises: 009_results
Create Date: 2026-05-15 20:04:52.852505

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'e6f84edec125'
down_revision: Union[str, None] = '009_results'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    
    # 1. Create field_comments table
    op.create_table('field_comments',
        sa.Column('id', sa.UUID(), nullable=False),
        sa.Column('field_id', sa.UUID(), nullable=False),
        sa.Column('author_id', sa.UUID(), nullable=False),
        sa.Column('comment', sa.String(), nullable=False),
        sa.Column('markers', postgresql.JSONB(astext_type=sa.Text()), nullable=True, comment='Array of {point: {lat, lng}, type, label}'),
        sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
        sa.ForeignKeyConstraint(['author_id'], ['users.id'], ),
        sa.ForeignKeyConstraint(['field_id'], ['fields.id'], ),
        sa.PrimaryKeyConstraint('id')
    )

    # 2. Add metadata to audit_logs
    op.add_column('audit_logs', sa.Column('metadata', postgresql.JSONB(astext_type=sa.Text()), nullable=True, comment='Additional context for the action'))

    # 3. Refine field_access roles (Removing CONSULTANT)
    op.alter_column('field_access', 'access_role',
               existing_type=sa.VARCHAR(length=10),
               type_=sa.Enum('OWNER', 'EDITOR', 'VIEWER', name='fieldaccessrole', native_enum=False),
               existing_nullable=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('field_access', 'access_role',
               existing_type=sa.Enum('OWNER', 'EDITOR', 'VIEWER', name='fieldaccessrole', native_enum=False),
               type_=sa.VARCHAR(length=10),
               existing_nullable=False)
    
    op.drop_column('audit_logs', 'metadata')
    op.drop_table('field_comments')
    # ### end Alembic commands ###
